services:
  frontend:
    build:
      target: dev
    env_file:
      - ./frontend/.env.development
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8082
      - REACT_APP_API_URL=http://localhost:8082
      - NODE_ENV=development
    ports:
      - "3000:3000"