services:
  - type: web
    name: yourjob-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 10000
    
  - type: web  
    name: yourjob-bff
    env: docker
    rootDir: bff
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 10000