[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
    "./gradlew clean bootJar --no-daemon",
    "ls -la build/libs/",
    "file build/libs/backend-app.jar"
]

[phases.start]
cmd = "java -jar ./build/libs/backend-app.jar"