[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = ["./gradlew clean bootJar --no-daemon"]

[phases.start]
cmd = "java -Dserver.port=$PORT -jar build/libs/backend-app.jar"

[variables]
PORT = "8080"