[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build] 
cmds = [
    "chmod +x ./gradlew",
    "./gradlew clean bootJar --no-daemon --stacktrace"
]

[phases.start]
cmd = "java -Dserver.port=$PORT -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar build/libs/backend-app.jar"

[variables]
GRADLE_OPTS = "-Dorg.gradle.daemon=false"