[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
    "./gradlew clean bootJar --no-daemon",
    "ls -la build/libs/"
]

[phases.start]
cmd = "java -Dserver.port=$PORT -jar build/libs/bff-app.jar"