[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build] 
cmds = [
    "ls -la ./gradlew",
    "chmod +x ./gradlew",
    "ls -la ./gradlew",
    "./gradlew --version",
    "./gradlew clean bootJar --no-daemon --stacktrace --info"
]

[phases.start]
cmd = "java -Dserver.port=$PORT -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar build/libs/bff-app.jar"

[variables]
GRADLE_OPTS = "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2048m"