
server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: bff
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

backend:
  url: "${BACKEND_URL:http://localhost:8082}"
  host: "${BACKEND_HOST:localhost}"
  port: "${BACKEND_PORT:8082}"

google:
  client:
    id: "${GOOGLE_CLIENT_ID:your-default-google-client-id}"
    secret: "${GOOGLE_CLIENT_SECRET:your-default-google-client-secret}"
  redirect:
    uri: "${GOOGLE_REDIRECT_URI:http://localhost:8083/api/v1/auth/callback}"

jwt:
  secret: ${JWT_SECRET:please-change-this-to-a-strong-32char-secret}

logging:
  level:
    com.yourjob.bff: DEBUG
    org.springframework.web: DEBUG