
google:
  client:
    id: "${GOOGLE_CLIENT_ID:your-default-google-client-id}"
    secret: "${GOOGLE_CLIENT_SECRET:your-default-google-client-secret}"
  redirect:
    uri: "${GOOGLE_REDIRECT_URI:http://192.168.100.101:8081/api/v1/auth/callback}"

backend:
  url: "${BACKEND_API_HOST}"

firebase:
  enabled=false

dummy:
  oauth:
    enabled: true