
jwt:
  secret: ${JWT_SECRET:please-change-this-to-a-strong-32char-secret}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:yourjobdb}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER:urjob}
    password: ${DB_PASSWORD:rootpass}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000
      pool-name: YourJobHikariCP
  servlet:
    multipart:
      enabled: true
      location: temp-uploads
      max-request-size: 300MB
      max-file-size: 50MB
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources.static-locations: file:/app/uploads/
  mail:
    host: ${SMTP_HOST:email-smtp.us-east-1.amazonaws.com}
    port: 587
    username: ${SMTP_USERNAME:your-smtp-username}
    password: ${SMTP_PASSWORD:your-smtp-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: no-reply@urjob.kr
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            redirect-uri: "${OAUTH_REDIRECT_URI:https://www.urjob.kr/login/oauth2/code/{registrationId}}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID:}
            client-secret: ${NAVER_CLIENT_SECRET:}
            redirect-uri: "${OAUTH_REDIRECT_URI:https://www.urjob.kr/login/oauth2/code/{registrationId}}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID:your-aws-access-key}
    secret-key: ${AWS_SECRET_ACCESS_KEY:your-aws-secret-key}
    region: ap-northeast-2
    bucket-name: urjob-uploads
    #cloudfront-domain: https://urjob-uploads.s3.ap-northeast-2.amazonaws.com
    cloudfront-domain: https://cdn.urjob.kr



storage:
  use-s3: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yourjob.backend.entity

server:
  port: ${SERVER_PORT:8082}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE:}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:tomcat}

servlet:
  multipart:
    enabled: true
    location: ${UPLOAD_TMP_DIR:/app/temp-uploads}
    max-request-size: 300MB
    max-file-size: 50MB

properties:
  values:
    domain: ${APP_DOMAIN:https://localhost}

